// Copyright (c) HiTechCloud Vietnam. SPDX-License-Identifier: MPL-2.0

package vportal

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hitechcloud-vietnam/terraform-provider-hitechcloud/client"
	"github.com/hitechcloud-vietnam/terraform-provider-hitechcloud/resource/common"
)

var (
	_ resource.Resource                = (*affiliateVoucherResource)(nil)
	_ resource.ResourceWithConfigure   = (*affiliateVoucherResource)(nil)
	_ resource.ResourceWithImportState = (*affiliateVoucherResource)(nil)
)

// AffiliateVoucherResource returns the hitechcloud_affiliate_adv_voucher resource.
func AffiliateVoucherResource() resource.Resource {
	return &affiliateVoucherResource{}
}

type affiliateVoucherResource struct {
	client *client.Client
}

type affiliateVoucherModel struct {
	ID        types.String `tfsdk:"id"`
	ClientID  types.String `tfsdk:"client_id"`
	PlanID    types.String `tfsdk:"plan_id"`
	Code      types.String `tfsdk:"code"`
	Discount  types.String `tfsdk:"discount"`
	Cycle     types.String `tfsdk:"cycle"`
	Expires   types.String `tfsdk:"expires"`
	MaxUsage  types.String `tfsdk:"max_usage"`
	Audience  types.String `tfsdk:"audience"`
	UsedCount types.String `tfsdk:"used_count"`
	Status    types.String `tfsdk:"status"`
}

func (r *affiliateVoucherResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_affiliate_adv_voucher"
}

func (r *affiliateVoucherResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages an advanced-affiliate discount voucher " +
			"(`POST /api/affiliates_adv/{client_id}/vouchers/{plan_id}`, " +
			"`DELETE /api/affiliates_adv/{client_id}/vouchers/{voucher_id}`).",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Voucher identifier returned by the API.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"client_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Affiliate client ID. Changing this forces a new resource.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"plan_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Commission plan ID the voucher belongs to. Changing this forces a new resource.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"code": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Voucher code; generated by the API when omitted. Changing this forces a new resource.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"discount": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Discount value of the voucher.",
			},
			"cycle": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Billing cycle the discount applies to.",
			},
			"expires": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Expiry date of the voucher.",
			},
			"max_usage": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Maximum number of redemptions.",
			},
			"audience": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Target audience of the voucher.",
			},
			"used_count": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Number of times the voucher has been redeemed.",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Current voucher status reported by the API.",
			},
		},
	}
}

func (r *affiliateVoucherResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	cli, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData),
		)
		return
	}
	r.client = cli
}

func (r *affiliateVoucherResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan affiliateVoucherModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := map[string]string{}
	if v := plan.Code.ValueString(); v != "" {
		params["code"] = v
	}
	if v := plan.Discount.ValueString(); v != "" {
		params["discount"] = v
	}
	if v := plan.Cycle.ValueString(); v != "" {
		params["cycle"] = v
	}
	if v := plan.Expires.ValueString(); v != "" {
		params["expires"] = v
	}
	if v := plan.MaxUsage.ValueString(); v != "" {
		params["max_usage"] = v
	}
	if v := plan.Audience.ValueString(); v != "" {
		params["audience"] = v
	}

	voucher, err := r.client.CreateAffiliateAdvVoucher(ctx,
		plan.ClientID.ValueString(),
		plan.PlanID.ValueString(),
		params,
	)
	if err != nil {
		resp.Diagnostics.AddError("Error creating affiliate voucher", err.Error())
		return
	}

	id := client.FirstString(voucher, "id", "voucher_id")
	if id == "" {
		id = plan.Code.ValueString()
	}
	plan.ID = types.StringValue(id)
	plan.Status = common.StringOrNull(client.FirstString(voucher, "status"))
	plan.UsedCount = common.StringOrNull(client.FirstString(voucher, "used_count", "used", "usage"))
	if v := client.FirstString(voucher, "code"); v != "" {
		plan.Code = types.StringValue(v)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *affiliateVoucherResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state affiliateVoucherModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	vouchers, err := r.client.ListAffiliateAdvVouchers(ctx, state.ClientID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading affiliate vouchers", err.Error())
		return
	}

	m, ok := client.FindByID(vouchers, state.ID.ValueString(), "id", "voucher_id")
	if !ok {
		resp.State.RemoveResource(ctx)
		return
	}
	state.Status = common.StringOrNull(client.FirstString(m, "status"))
	state.UsedCount = common.StringOrNull(client.FirstString(m, "used_count", "used", "usage"))
	state.Discount = common.StringOrNull(client.FirstString(m, "discount"))
	state.Cycle = common.StringOrNull(client.FirstString(m, "cycle"))
	state.Expires = common.StringOrNull(client.FirstString(m, "expires", "expiry"))
	state.MaxUsage = common.StringOrNull(client.FirstString(m, "max_usage", "max"))
	state.Audience = common.StringOrNull(client.FirstString(m, "audience"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Vouchers cannot be edited after creation: Update is only reached via replacement.
func (r *affiliateVoucherResource) Update(_ context.Context, _ resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError(
		"Affiliate vouchers are immutable",
		"The API does not support editing vouchers; this resource only supports create, read and delete.",
	)
}

func (r *affiliateVoucherResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state affiliateVoucherModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.client.DeleteAffiliateAdvVoucher(ctx,
		state.ClientID.ValueString(),
		state.ID.ValueString(),
	); err != nil && !client.IsNotFound(err) {
		resp.Diagnostics.AddError("Error deleting affiliate voucher", err.Error())
	}
}

func (r *affiliateVoucherResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	id := req.ID
	parts, err := client.SplitID(id, 2)
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf(
			"Expected import ID in the format client_id/voucher_id: %s", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), parts[1])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("client_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("plan_id"), "0")...)
}
